### PR TITLE
Request to re-model the layout and added extra code

### PR DESCRIPTION
**Pull request by dannysmc95**
Hello I have added all the layout for files and added all the code that I have currently. Please check and tell me what you think.

I see a lot of people have added code, this code isn't lost it is just in the Other folder inside src. As of now the layout structure you have seems to be "messy" not in a rude way, I would like to re-model it so it is easier to deal with then make everything that belongs to that folder in that folder. client.lua is the first main code I have made which will be used. I have a lot of spare time at work so I will be pushing a lot. As the ideas I have are coming together.

### CODE REVIEW

**Comment by lupus590** [comment]
I am aware that it is messy, that's what you get when you decide to design a system as you go.

**Comment by dannysmc95** [comment]
Yeah that's fair enough, well yeah I have a big update for everything and am currently adding the menu.

**Comment by lupus590** [comment]
What does the logo spell? I like the hexagons in it but can see the bottom word (top says hive from what I can tell)

**Comment by dannysmc95** [comment]
SYST, as I didn't want to make the logo huge and I couldn't think of anything else, so yeah added the SYST as a Hive System, but syst for short.

**Comment by lupus590** [comment]
@TheOnlyCreator wants to use IPnet for communication, I have said that rednet should at least be a fall back, you two may need to cooperate on this.

**Comment by dannysmc95** [comment]
Hmm I am not sure about using IPnet, i would preferably use our own code. Not someone else's as I plan to have a lot more than string sent between them. So of course it is your project but I have a lot more to add yet and I would rather we work together to make our own version of course I would not want to make that but I would happy to be open to ideas and code sketches. I have to ask will you be allowing the request or not? As If not I will keep it on my repo. But of course it won't be on yours.

**Comment by lupus590** [comment]
I wanted to use the rednet networks that users would already have, and be usable off-line, so I know what you mean.

**Comment by dannysmc95** [comment]
Okay well I will use rednet which was the plan I wanted to do anyway as I need to use the protocols inside rednet.

**Comment by lupus590** [comment]
There is some third party code that will will be using though, such as LAMA and starNav for turtles, nsh for bottom level error recovery (entire program broke on a turtle? fix it while at home), and touchpoint for buttons.

**Comment by dannysmc95** [comment]
Everything is okay other than touchpoint, as I would prefer to make my own touch interface. So I can allow what I need, I need have a little more control. If touchpoint is usable on monitors then we can use it for that, but not for the Computer, if that's okay?

**Comment by lupus590** [comment]
touchpoint is MIT, and I planned to modify it anyway. If you can, add functionality to touchpoint

**Comment by dannysmc95** [comment]
Eh I will have a look but for the best part I won't be using it yet until I have a basic system working.

When are you merging this?

**Comment by lupus590** [comment]
I was pushing some of my changes

**Comment by lupus590** [comment]
Part of what I wanted to do was make hive more of an API and have a gui/command-line sit on it

**Comment by dannysmc95** [comment]
That's fine with me. Cheers anyway, can I push to your master? or is that still a no?

**Comment by dannysmc95** [comment]
Yes that was what I was aiming for too!

**Comment by dannysmc95** [comment]
The server is a walking api, the client just utilizes the servers commands to functions

**Comment by lupus590** [comment]
not yet, I want to check everyone's coding style before they get free range on my repo

**Comment by dannysmc95** [comment]
That's okay with me!

**Comment by dannysmc95** [comment]
Just please make sure to keep with that layout as it makes it a lot neater and I would prefer it like that if that is okay? Cheers.

**Comment by dannysmc95** [comment]
Where can we discuss the updates on here? Talk about what to change etc? I will probably be making a pull request a day. So be prepared, I code quite quickly! if that's not a problem?

**Comment by lupus590** [comment]
I will be changing it a bit. If your code is good I will add you as a collaborator.

**Comment by dannysmc95** [comment]
yeah okay!

**Pull request merged**
